name: aniflix_app
description: App for Aniflix

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.11+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  image_picker:
  dio:
  flutter_bcrypt:
  simple_permissions:
    git:
      url: https://github.com/tq-systems/simple_permissions.git
  path_provider:
  flutter_downloader: 1.4.4
  titled_navigation_bar:
  cached_network_image:
  video_player:
  neeko:
  bmnav:
  http:
  url_launcher:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.4+3
  expandable: ^3.0.1
  smooth_star_rating: 1.0.3
  firebase_messaging:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_analytics:
  flutter_native_admob:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: ^2.2.1
  flutter_gherkin:
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  flutter_driver:
    sdk: flutter
  test: any


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/ger.png
    - assets/images/gerjap.png
    - assets/images/jap.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
