name: Generate Metrics for App

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  metrics:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
      - uses: actions/checkout@v2
      - run: pub global activate dart_code_metrics
      - run: pub global run dart_code_metrics:metrics lib
